name: CI
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  Linter:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: cd aula1 && npm install
      - name: Run Linter
        run: cd aula1 && npm run lint
      - name: Run Prettier
        run: cd aula1 && npm run prettier
      - name: Run Tests
        run: cd aula1 && npm run test
      - name: Run Build
        run: cd aula1 && npm run build
      - name: Run Deploy
        env:
          NETLIFY_SITE_ID: ${{ vars.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ vars.NETLIFY_AUTH_TOKEN }}
        run: cd aula1 &&  npx netlify-cli deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
